package com.tdm.model.DTO;

public enum ActivityScreenName {
	LOGIN,
	LOGOUT,
	DATA_MINING,
	SERVICE_DESK,
	MY_REQUESTS,
	MY_RESERVATIONS,
	DATA_GENERATION_MANUAL,
	DATA_GENERATION_AUTO,
	GOVERNANCE,
	LANDING_PAGE,
	REGISTRATION,
	CONTACT_US,
}
