DROP TABLE DM_AMOUNT_STG;
DROP TABLE DM_COVERAGE_RISK_STG;
DROP TABLE DM_COVERAGE_STG;
DROP TABLE DM_NO_OF_DRIVER_STG;
DROP TABLE DM_NO_OF_NAME_INSU_STG;
DROP TABLE DM_NO_OF_VEHI_STG;
DROP TABLE DM_NO_OF_VIO_STG;
DROP TABLE DM_POLICY_SUMMARY_STG;
COMMIT;

--------------------------------------------------------
--  DDL for Table DM_POLICY_SUMMARY_STG
--------------------------------------------------------

  CREATE TABLE "DM_POLICY_SUMMARY_STG" 
   (	"POLICYNUMBER" VARCHAR2(50 BYTE) NOT NULL, 
	"LOB" VARCHAR2(20 BYTE), 
	"POLICYSTATUSCD" VARCHAR2(50 BYTE), 
	"POLICYFORMCD" VARCHAR2(50 BYTE), 
	"TIMEDPOLICYSTATUSCD" VARCHAR2(20 BYTE), 
	"TXTYPE" VARCHAR2(20 BYTE), 
	"CONTRACTTERMTYPECD" VARCHAR2(20 BYTE), 
	"PRODUCTCD" VARCHAR2(20 BYTE), 
	"RISKSTATECD" VARCHAR2(20 BYTE), 
	"EFFECTIVE" DATE, 
	"EXPIRATION" DATE, 
	"POLICYDETAIL_ID" VARCHAR2(20 BYTE), 
	"CURRENTREVISIONIND" VARCHAR2(20 BYTE), 
	"PAYMENTPLANCD" VARCHAR2(20 BYTE), 
	"PAYMENT_FREQUENCY" VARCHAR2(20 BYTE)
, CONSTRAINT DM_POLICY_SUMMARY_STG_PK PRIMARY KEY 
  (
    POLICYDETAIL_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX DM_POLICY_SUMMARY_STG_PK ON DM_POLICY_SUMMARY_STG (POLICYDETAIL_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE INDEX DM_POLICY_SUMMARY_STG_INDEX1 ON DM_POLICY_SUMMARY_STG (POLICYNUMBER ASC, POLICYDETAIL_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;


--------------------------------------------------------
--  DDL for Table DM_COVERAGE_STG
--------------------------------------------------------

CREATE TABLE "DM_COVERAGE_STG" 
   (	"ID" VARCHAR2(50 BYTE), 
	"POLICYDETAIL_ID" VARCHAR2(50 BYTE), 
	"COVERAGECD" VARCHAR2(50 BYTE)
 ) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE INDEX DM_COVERAGE_STG_INDEX1 ON DM_COVERAGE_STG (POLICYDETAIL_ID ASC, COVERAGECD ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE DM_COVERAGE_STG
ADD CONSTRAINT DM_COVERAGE_STG_FK1 FOREIGN KEY
(
  POLICYDETAIL_ID 
)
REFERENCES DM_POLICY_SUMMARY_STG
(
  POLICYDETAIL_ID 
)
ENABLE;




CREATE TABLE DM_COVERAGE_RISK_STG 
(
  ID VARCHAR2(50) NOT NULL 
, POLICYDETAIL_ID VARCHAR2(50) NOT NULL 
, COVERAGECD VARCHAR2(50) 
, CONSTRAINT DM_COVERAGE_RISK_STG_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE INDEX DM_COVERAGE_RISK_STG_INDEX1 ON DM_COVERAGE_RISK_STG (POLICYDETAIL_ID ASC, COVERAGECD ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE DM_COVERAGE_RISK_STG
ADD CONSTRAINT DM_COVERAGE_RISK_STG_FK2 FOREIGN KEY
(
  POLICYDETAIL_ID 
)
REFERENCES DM_POLICY_SUMMARY_STG
(
  POLICYDETAIL_ID 
)
ON DELETE CASCADE ENABLE;


 
CREATE TABLE DM_NO_OF_DRIVER_STG 
(
  POLICYDETAIL_ID VARCHAR2(50) NOT NULL 
, COUNT NUMBER(5, 0) DEFAULT 0 NOT NULL 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE INDEX DM_NO_OF_DRIVER_STG_INDEX1 ON DM_NO_OF_DRIVER_STG (POLICYDETAIL_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE DM_NO_OF_DRIVER_STG
ADD CONSTRAINT DM_NO_OF_DRIVER_STG_UK1 UNIQUE 
(
  POLICYDETAIL_ID 
)
USING INDEX DM_NO_OF_DRIVER_STG_INDEX1
ENABLE;

ALTER TABLE DM_NO_OF_DRIVER_STG
ADD CONSTRAINT DM_NO_OF_DRIVER_STG_FK1 FOREIGN KEY
(
  POLICYDETAIL_ID 
)
REFERENCES DM_POLICY_SUMMARY_STG
(
  POLICYDETAIL_ID 
)
ENABLE;



CREATE TABLE DM_NO_OF_VEHI_STG 
(
  POLICYDETAIL_ID VARCHAR2(50) NOT NULL 
, COUNT NUMBER(5, 0) DEFAULT 0 NOT NULL 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE INDEX DM_NO_OF_VEHI_STG_INDEX1 ON DM_NO_OF_VEHI_STG (POLICYDETAIL_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE DM_NO_OF_VEHI_STG
ADD CONSTRAINT DM_NO_OF_VEHI_STG_UK1 UNIQUE 
(
  POLICYDETAIL_ID 
)
USING INDEX DM_NO_OF_VEHI_STG_INDEX1
ENABLE;

ALTER TABLE DM_NO_OF_VEHI_STG
ADD CONSTRAINT DM_NO_OF_VEHI_STG_FK1 FOREIGN KEY
(
  POLICYDETAIL_ID 
)
REFERENCES DM_POLICY_SUMMARY_STG
(
  POLICYDETAIL_ID 
)
ENABLE;




CREATE TABLE DM_NO_OF_NAME_INSU_STG 
(
  POLICYDETAIL_ID VARCHAR2(50) NOT NULL 
, COUNT NUMBER(5, 0) NOT NULL 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE INDEX DM_NO_OF_NAME_INSU_STG_INDEX1 ON DM_NO_OF_NAME_INSU_STG (POLICYDETAIL_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE DM_NO_OF_NAME_INSU_STG
ADD CONSTRAINT DM_NO_OF_NAME_INSU_STG_UK1 UNIQUE 
(
  POLICYDETAIL_ID 
)
USING INDEX DM_NO_OF_NAME_INSU_STG_INDEX1
ENABLE;

ALTER TABLE DM_NO_OF_NAME_INSU_STG
ADD CONSTRAINT DM_NO_OF_NAME_INSU_STG_FK1 FOREIGN KEY
(
  POLICYDETAIL_ID 
)
REFERENCES DM_POLICY_SUMMARY_STG
(
  POLICYDETAIL_ID 
)
ENABLE;




CREATE TABLE DM_NO_OF_VIO_STG 
(
  POLICYDETAIL_ID VARCHAR2(50) NOT NULL 
, COUNT NUMBER(5, 0) NOT NULL 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE INDEX DM_NO_OF_VIO_STG_INDEX1 ON DM_NO_OF_VIO_STG (POLICYDETAIL_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE DM_NO_OF_VIO_STG
ADD CONSTRAINT DM_NO_OF_VIO_STG_UK1 UNIQUE 
(
  POLICYDETAIL_ID 
)
USING INDEX DM_NO_OF_VIO_STG_INDEX1
ENABLE;

ALTER TABLE DM_NO_OF_VIO_STG
ADD CONSTRAINT DM_NO_OF_VIO_STG_FK1 FOREIGN KEY
(
  POLICYDETAIL_ID 
)
REFERENCES DM_POLICY_SUMMARY_STG
(
  POLICYDETAIL_ID 
)
ENABLE;

--------------------------------------------------------
--  DDL for Table DM_AMOUNT_STG
--------------------------------------------------------

  CREATE TABLE "DM_AMOUNT_STG" 
   (	"POLICYNUMBER" VARCHAR2(50 BYTE), 
	"AMT_DUE" NUMBER, 
	"AMT_DUE_FLAG" CHAR(1 BYTE), 
	"MIN_AMT_DUE" NUMBER, 
	"MIN_AMT_DUE_FLAG" CHAR(1 BYTE)
	, CONSTRAINT DM_AMOUNT_STG_PK PRIMARY KEY 
  (
    POLICYNUMBER 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE INDEX DM_AMOUNT_STG_INDEX1 ON DM_AMOUNT_STG (POLICYNUMBER ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

COMMIT;