DELETE FROM DM_AMOUNT_STG;
DELETE FROM DM_COVERAGE_RISK_STG;
DELETE FROM DM_COVERAGE_STG;
DELETE FROM DM_NO_OF_DRIVER_STG;
DELETE FROM DM_NO_OF_NAME_INSU_STG;
DELETE FROM DM_NO_OF_VEHI_STG;
DELETE FROM DM_NO_OF_VIO_STG;
DELETE FROM DM_POLICY_SUMMARY_STG;